name: Node.js CI

on:
  push:
    branches:
      - master
      - "fiddl*"
    tags:
      - '[vV]?[0-9]+.[0-9]+.[0-9]+' # tolerate with and without leading `v`
  pull_request:
    branches: [master]

jobs:
  lint:
    # REF if: github.ref == 'refs/heads/master' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm i jsdoc #  yes, just `npm install`, no `npm ci` <-> no package-lock.json
      - run: npm run lint

  jsdoc:
    # build jsdoc only on pushed tags (commonly new pushed version)
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm i jdoc
      - run: npm run doc
      - name: Commit JSDoc
        uses: EndBug/add-and-commit@v9
        env:
          # get version from environment variable
          VERSION: ${{ env.VERSION }}
        with:
          default_author: github_actions
          add: "docs/*"
          message: "update jsdocs $VERSION"

  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 19.x ] # later again [16.x, 19.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm i (yes, just install, no package-lock.json)
        run: npm i
      - run: npm test

# REF test comment .....
