name: Node.js CI

on:
  push:
    branches:
      - master
      - 'fiddl*'
  pull_request:
    branches: [master]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm i
        name: npm i (yes, just install, no ci<->no package-lock.json)
      - run: npm run lint

  jsdoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm i
      - run: npm run doc
      - name: Commit JSDoc
        uses: EndBug/add-and-commit@v9
        with:
          add: "docs/*"
          message: "Generate JSDoc"
          author_name: "github workflows"

  build:
    runs-on: ubuntu-latest
    #test comment

    strategy:
      matrix:
        node-version: [16.x, 19.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm i (yes, just install, no package-lock.json)
        run: npm i
      - run: npm test

# REF test comment ...
